name: node

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_run:
    branches: [ $default-branch ]
  workflow_dispatch:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - name: send message
      uses: appleboy/telegram-action@0.0.3
      env:
        TELEGRAM_TOKEN: ${{ secrets.telegram_token }}
        TELEGRAM_TO: ${{ secrets.telegram_to }}
      with:
        message: |
          ${{ github.repo }} repo with ${{ github.event_name }} event triggered,
          final status is {{ job.status }}.
